version: "3"

services:
  client:
    build:
      context: .
    image: rent-it-backend-img
    container_name: rent-it-backend
    restart: always
  redis:
    image: redis
    container_name: rent-it-redis
    restart: always
  pg-socket:
    image: ashrhmn/pg-socket
    container_name: rent-it-pg-socket
    restart: always
    env_file:
      - .env
networks:
  default:
    external: true
    name: nginx
