version: "3"

services:
  client:
    build:
      context: .
    image: rent-it-backend-img
    container_name: rent-it-backend
    restart: always
  redis:
    image: redis
    container_name: rent-it-redis
    restart: always
networks:
  default:
    external: true
    name: nginx
